### ISSUE TITLE
Could not start basic search in project

### ISSUE THREAD

**Issue by dengelMonguz** [mol-pl/z3950-server#33]
I'm a few hours into this project and would like to run a succesful search on it with some result but could not make it yet.

The project was built with 1.7 java, then started with tomcat 8.5.59
Then I tried with the BibDataZu client (LOC supported) to call for the port and issue a simple search, but it faild. The error log hints that it is duo to an unknown collection [Test], but it is stated in JZKitConfig.xml that there is a dummy collection for testing.
Is there a way to try out this project or a step-to-step guid that helps to run and test the project?
![error](https://user-images.githubusercontent.com/41684473/96465587-6907a580-1229-11eb-9ca2-fd87a7e20455.jpg)
![search](https://user-images.githubusercontent.com/41684473/96465766-9e13f800-1229-11eb-92ec-52cd4af727d0.jpg)

**Comment by kanasznagyzoltan** [comment]
I have also tried this project to use as a Z39.50 server. So far we could not manage to work unfortunately... 

What we have done
- built the project successfully with JDK 7 
- installed into Tomcat 8
- tried to connect to it and tried to search using the Example ResultSet

Could someone give us a short tutorial how this server is working. If some additional config needed could you post that config?

Thank you!
We are really much appreciate your help!

**Comment by Eccenux** [comment]
Hi. This project is mostly provided AS-IS. It works and builds on JDK 7 with Maven. JDK8 should work as well for building, but probably not for running it.

In any case you still need to implement search features in the actual backend. This is mostly just a proxy for another HTTP/HTTPS service. You should probably rewrite all classes in `pl.mol` namespaces.

Or you can use original jzkit. I see previous website is gone. But this is probably the same: https://sourceforge.net/projects/jzjkit/files/.

We are not creators of the library and we don't provide support to it. Sorry about that. But good luck 🙂.
